language: node_js
node_js:
  - "7"
jobs:
  include:
    - stage: npm build
      node_js: "7"
      deploy:
        provider: npm
        email: $email
        api_key: $token
        on:
            tags: true